package com.unimate.unimate.enums;

public enum AccessCode {
    ACCEPT_PAYMENT, LIMITING_DISCOUNT, CHANGE_TAX, CASH_REGISTER, VIEW_RECEIPT, PURCHASE_RETURN, PRINT_SEND_RECEIPT, CHANGE_ITEM, POS_VIEW_ITEM_COST, VIEW_SETTING,
    VIEW_SALES, CANCEL_RECEIPT, MANAGE_ITEM, BO_VIEW_ITEM_COST, MANAGE_EMPLOYEE, CUSTOMER_BASE, PROFILE, BILLING, MANAGE_PAYMENT_TYPE, MANAGE_LOYALTY_PROGRAM, MANAGE_TAX, MANAGE_POS_DEVICE
}
